name: Deploy to Netlify

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build project
      - name: Build project
        run: npm run build

      # Deploy using Netlify CLI
      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --dir=dist --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
