name: Deploy Frontend to Netlify

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Go into frontend folder
      - name: Go to frontend folder
        run: cd sample-netlify-app/app

      # Install dependencies
      - name: Install dependencies
        run: |
          cd sample-netlify-app
          npm install

      # Build project
      - name: Build project
        run: |
          cd sample-netlify-app/app
          npm run build

      # Deploy to Netlify
      - name: Deploy to Netlify
        run: |
          cd sample-netlify-app/app
          npm install -g netlify-cli
          netlify deploy --dir=dist --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
